FROM centos7-base
Maintainer Georg Rabenstein <georg.rabenstein@deposit-solutions.com>

USER root 

RUN yum -y install python gcc python-devel python-setuptools-devel && yum clean all
RUN easy_install pip
